version: '3.7'

services:
    nginx:
        container_name: randomovies_nginx_dev
        image: nginx:latest
        env_file: ./.env
        volumes:
            - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            # - ./web/:/app/
            - ./:/opt/project/
            - ./var/log/nginx/:/var/log/nginx/
        networks:
            - randomovies
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.backend=randomovies"
            - "traefik.backend.loadbalancer.method=drr"
            - "traefik.frontend.rule=Host:randomovies.localhost"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.port=80"
            - "traefik.docker.network=traefik"
        depends_on:
            - php
        ports:
            - 8002:80

    php:
        container_name: randomovies_php_dev
        build:
            context: ./docker/php/
        depends_on:
            - database
        env_file: ./.env
        volumes:
            - ./:/opt/project/
            # - ./docker/php/ini/:/usr/local/etc/php/
        environment:
            - SYMFONY_ENV=${SYMFONY_ENV}
            - MYSQL_PORT=${DATABASE_PORT}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        networks:
          - randomovies

#    randomovies_database:
#        image: mariadb:latest
#        # image: mariadb:10.1.21
#        volumes:
#            - ./docker/database/data:/var/lib/mysql
#            # marche pas sous windows en NTFS
#        env_file: ./.env
#        environment:
#            - MYSQL_PORT=${DATABASE_PORT}
#            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
#            - MYSQL_DATABASE=${DATABASE_NAME}
#            - MYSQL_USER=${DATABASE_USER}
#            - MYSQL_PASSWORD=${DATABASE_PASSWORD}

    database:
        container_name: randomovies_database_dev
        image: mariadb:10.4.4-bionic
        # image: mariadb:10.1.21
        volumes:
            - ./docker/database/data:/var/lib/mysql
            # marche pas sous windows en NTFS
        env_file: ./.env
        environment:
            - MYSQL_PORT=${DATABASE_PORT}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        networks:
          - randomovies

    phpmyadmin:
        container_name: randomovies_phpmyadmin_dev
        image: phpmyadmin/phpmyadmin
        env_file: ./.env
        links:
            - database
        environment:
            - PMA_HOST=${DATABASE_HOST}
        networks:
            - randomovies
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.backend=pma.randomovies"
            - "traefik.backend.loadbalancer.method=drr"
            - "traefik.frontend.rule=Host:pma.randomovies.localhost"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.docker.network=traefik"

    elasticsearch:
        container_name: randomovies_elasticsearch_dev
#        image: elasticsearch:5.3
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2        
        environment:
          - cluster.name=docker-cluster
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
            - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
#        restart: always
        networks:
            - randomovies
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.backend=es.randomovies"
            - "traefik.backend.loadbalancer.method=drr"
            - "traefik.frontend.rule=Host:es.randomovies.localhost"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.port=${ELASTIC_PORT}"
            - "traefik.docker.network=traefik"
        ports:
            - 8004:9200
            - 8005:9300
#            - 8005:92000

    node:
        container_name: randomovies_node_dev
        build:
            context: ./docker/node/
            dockerfile: ./Dockerfile
        volumes:
            - ./:/usr/src/app/

    mailcatcher:
        container_name: randomovies_mailcatcher_dev
        image: schickling/mailcatcher
        ports:
            - "1025:1025"
        networks:
            - randomovies
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.backend=mailcatcher.randomovies"
            - "traefik.backend.loadbalancer.method=drr"
            - "traefik.frontend.rule=Host:mailcatcher.randomovies.localhost"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.port=1080"
            - "traefik.docker.network=traefik"

networks:
    randomovies:
        name: randomovies
    traefik:
        external: true