version: '3'

services:
    randomovies_nginx:
        image: nginx:latest
        env_file: ./.env
        volumes:
            - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            # - ./web/:/app/
            - ./:/opt/project/
            - ./var/logs/nginx/:/var/log/nginx/
        labels:
            - "traefik.backend=randomovies_nginx"
            - "traefik.frontend.rule=Host:${SITE_HOST}"
            - "traefik.port=80"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.backend.loadbalancer.method=drr"
        depends_on:
            - randomovies_php
        ports:
            - 8002:80

    randomovies_php:
        build:
            context: ./docker/php/
        depends_on:
            - randomovies_database
        env_file: ./.env
        volumes:
            - ./:/opt/project/
            # - ./docker/php/ini/:/usr/local/etc/php/
        environment:
            - SYMFONY_ENV=${SYMFONY_ENV}
            - MYSQL_PORT=${DATABASE_PORT}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        labels:
            - "traefik.enable=false"

    randomovies_database:
        image: mariadb:latest
        # image: mariadb:10.1.21
        volumes:
            - ./docker/database/data:/var/lib/mysql
            # marche pas sous windows en NTFS
        env_file: ./.env
        environment:
            - MYSQL_PORT=${DATABASE_PORT}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}

    randomovies_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        env_file: ./.env
        links:
            - randomovies_database
        environment:
            - PMA_HOST=${DATABASE_HOST}
        labels:
            - "traefik.backend=randomovies_phpmyadmin"
            - "traefik.frontend.rule=Host:pma.${SITE_HOST}"
            - "traefik.backend.loadbalancer.method=drr"
            - "traefik.frontend.passHostHeader=true"

    randomovies_elasticsearch:
        image: elasticsearch:5.3
        restart: always
        labels:
            - "traefik.backend=randomovies_elasticsearch"
            - "traefik.frontend.rule=Host:es.${SITE_HOST}"
            - "traefik.port=${ELASTIC_PORT}"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.backend.loadbalancer.method=drr"
        ports:
            - 8004:9200
            - 8005:9300
#            - 8005:92000

    randomovies_node:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
        volumes:
            - ./:/usr/src/app/

    randomovies_mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1025:1025"
        labels:
            - "traefik.backend=mailcatcher"
            - "traefik.frontend.rule=Host:mailcatcher.${SITE_HOST}"
            - "traefik.port=1080"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.backend.loadbalancer.method=drr"

networks:
    default:
        external:
            name: devtools