<?php

namespace AppBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
	public function getOrderedMoviesByTitle()
	{
		return $this->getEntityManager()
			->createQueryBuilder()
			->select('m')
			->from('AppBundle:Movie', 'm')   
			->orderBy('m.title', 'ASC')
			->getQuery()
			->getResult()			
		;
	}
}
