fos_elastica:
    clients:
#        default: { host: %elastic_host%, port: %elastic_port% }
#        default: { host: '%env(ELASTIC_HOST)%', port: '%env(ELASTIC_PORT)%' }
#        default: { host: 172.18.0.16, port: '%env(ELASTIC_PORT)%' }
        default: { url: '%env(ELASTIC_URL)%' }
    indexes:
        randomovies:
            client: default
            types:
                movie:
                    mappings:
                        id:
                            type: integer
                        title: { search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string }
                        director: ~
                        actors: ~
                        year:
                            type: integer
                        duration:
                            type: integer
                        # synopsis: ~
                        rating:
                            type: integer
                        genre: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Movie
                        finder: ~
                        provider: ~
                        listener: ~
                        repository: AppBundle\Entity\MovieSearchRepository