# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
#    app.doctrine_poster_listener:
#        class: AppBundle\EventListener\PosterUploadListener
#        arguments: ['%posters_directory%']
#        tags:
##            - { name: doctrine.event_listener, event: prePersist }
##            - { name: doctrine.event_listener, event: preUpdate }
#            - { name: doctrine.event_listener, event: postLoad }

    app.movie_persist_listener:
        class: AppBundle\EventListener\MoviePersistListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
#            - { name: doctrine.event_listener, event: postFlush }

    app.twig.random_movies_extension:
        class: AppBundle\Twig\Extension\RandomMoviesExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    app.twig.total_users_notes:
        class: AppBundle\Twig\Extension\TotalUsersNotesExtension
        tags:
            - { name: twig.extension }