# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.doctrine_poster_listener:
        class: AppBundle\EventListener\PosterUploadListener
        arguments: ['%posters_directory%']
        tags:
            # - { name: doctrine.event_listener, event: prePersist }
            # - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }