<?php

namespace Randomovies\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
	public function getOrderedMoviesByTitle($startAt = 0, $endAt = 6, $params = [])
	{
		$queryBuilder = $this->getEntityManager()
			->createQueryBuilder()
			->select('m')
			->from('Randomovies:Movie', 'm')
            ->leftJoin('m.tags', 't')
            ->where('m.title != \'\'')
			->orderBy('m.title', 'ASC')
            ->setFirstResult($startAt)
            ->setMaxResults($endAt)
        ;

        foreach ($params as $param) {
            $queryBuilder
                ->andWhere($param['andWhere'])
                ->setParameter($param['value'][0], $param['value'][1])
            ;
        }

		return $queryBuilder
			->getQuery()
			->getResult()			
		;
	}

	public function getRandomMovies($nb = 4)
    {
        $results = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('m')
            ->from('Randomovies:Movie', 'm')
            ->orderBy('m.title', 'ASC')
            ->getQuery()
            ->getResult()
        ;

        $fourRandoNb = [];
        while (count($fourRandoNb) !== 5) {
            $randoNb = mt_rand(0, count($results)-1);
            if (!(in_array($randoNb, $fourRandoNb))) {
                $fourRandoNb[] = $randoNb;
            }
        }

        $fourMovies = [];

        foreach($fourRandoNb as $oneRandoNb) {
            $fourMovies[] = $results[$oneRandoNb];
        }

        return $fourMovies;
    }

    public function getDistinctCategories()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('m.genre')
            ->from('Randomovies:Movie', 'm')
            ->orderBy('m.genre', 'asc')
            ->distinct()
            ->getQuery()
            ->getResult()
        ;
    }

    public function getTotalMovies($params = [])
    {
        $queryBuilder = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('COUNT(m)')
            ->from('Randomovies:Movie', 'm')
            ->leftJoin('m.tags', 't')
            ->where('m.title != \'\'')
        ;

        foreach ($params as $param) {
            $queryBuilder
                ->andWhere($param['andWhere'])
                ->setParameter($param['value'][0], $param['value'][1])
            ;
        }

        return $queryBuilder
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }
}
