<?php

namespace Randomovies\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrderedActorsByName()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('Randomovies:Person', 'p')
            ->orderBy('p.lastname', 'ASC')
            ->getQuery()
            ->getResult()
            ;
    }
    
    public function getTotalPeople()
    {
        return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('COUNT(p)')
        ->from('Randomovies:Person', 'p')
        ->getQuery()
        ->getSingleScalarResult()
        ;
    }
}
