imports:
#    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: fos_elastica.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # posters_directory: '%kernel.root_dir%/../web/images/posters'
    medias_directory: '%kernel.project_dir%/public/images/medias'
    posters_directory: '%kernel.project_dir%/public/images/posters'
    users_photos_directory: '%kernel.project_dir%/public/images/users/photos'
    max_results_by_page: 6

    elastic_host: localhost
    elastic_port: 9200

    database_host: randomovies_database
    database_port: 3306
    database_name: randomovies
    database_user: randomovies
    database_password: azerty123

#    mailer_transport: smtp
    mailer_transport: gmail
    mailer_host: 127.0.0.1
    mailer_username: benjamin.billette@gmail.com
    mailer_password: 1987arqfwv
    mailer_sender: contact@randomovies.fr

    secret: ThisTokenIsNotSoSecretChangeIt

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%env(SECRET)%'
    router:
        resource: '%kernel.project_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.project_dir%/var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    serializer:
        enabled: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: '%env(DATABASE_DRIVER)%'
        host: '%env(MYSQL_HOST)%'
        port: '%env(MYSQL_PORT)%'
        dbname: '%env(MYSQL_DATABASE)%'
        user: '%env(MYSQL_USER)%'
        password: '%env(MYSQL_PASSWORD)%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
           Randomovies:
              alias: Randomovies
              dir: '%kernel.project_dir%/src/Entity'
              is_bundle: false
              prefix: 'Randomovies\Entity'
              type: annotation

#doctrine_migrations:
#    dir_name: "%kernel.root_dir%/Migrations"
#    namespace: Randomovies\Migrations

# Swiftmailer Configuration
#swiftmailer:
#    delivery_addresses: ['benjamin.billette@hotmail.fr%']
#    transport: '%mailer_transport%'
##    host: '%mailer_host%'
#    username: '%mailer_username%'
#    password: '%mailer_password%'
##    spool: { type: memory }

swiftmailer:
    delivery_addresses: ['benjamin.billette@hotmail.fr%']
    transport: smtp
    host: 'mailcatcher'
    port: 1025
    username: null
    password: null