imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }    
    - { resource: elasticsearch.yml }
    - { resource: easyadmin.yml }

parameters:
    locale: fr_FR
    medias_directory: '%kernel.project_dir%/public/images/medias'
    posters_directory: '%kernel.project_dir%/public/images/posters'
    users_photos_directory: '%kernel.project_dir%/public/images/users/photos'
    max_movies_per_page: 20
    max_comments_per_page: 20
    admin_max_results_per_page: 30

framework:
    translator: { fallbacks: [ "fr" ] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.project_dir%/var/sessions/%kernel.environment%"
        # pour que ça marche avec virtualbox
        # save_path:   /var/lib/php/sessions
    fragments: ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/css/asset_manifest.json'
    php_errors:
        log: true
    serializer:
        enabled: true

twig:
    debug: '%kernel.debug%'
    globals:
        randomovies_domain: '%randomovies_domain%'
    strict_variables: '%kernel.debug%'

doctrine:
    dbal:
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
           Randomovies:
              alias: Randomovies
              dir: '%kernel.project_dir%/src/Entity'
              is_bundle: false
              prefix: 'Randomovies\Entity'
              type: annotation

swiftmailer:
    delivery_addresses: ['%mailer_delivery%']
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'