easy_admin:
    design:
        brand_color: '#a55eea'
    entities:
        User:
            class: Randomovies\Entity\User
            form:
                fields:
                    - username
                    - firstname
                    - lastname
#                    - { property: 'birthdate', type_options: { required: false } }
                    - { property: 'birthdate', label: 'Date de naissance', type_options: {'widget': 'single_text', 'format': 'dd/MM/yyyy', 'attr': {'class': 'datepicker'}, required: false} }
                    - email
                    - roles
                    - isActive
                    - { property: 'plainPassword', type: 'text', type_options: { required: false, empty_data: '' } }
        Review:
            class: Randomovies\Entity\Review
            list:                
                fields: ['id', 'movie.title', 'user.username', 'rating', 'review', 'createdAt', 'main']
            form:
                fields: ['rating', 'review', 'main']        
        Comment:
            class: Randomovies\Entity\Comment
            list:                
                fields: ['id', 'createdAt', 'movie.title', 'user.username', 'comment', 'note']
            form:
                fields: ['comment', 'note']
        Suggestion:
            class: Randomovies\Entity\Suggestion
            list:
                actions: ['create']
                fields: ['id', 'movieTitle', 'user.username', 'suggestedAt', 'treatedAt']                
            form:
                fields: ['treatedAt']