fos_elastica:
    clients:
#        default: { host: %elastic_host%, port: %elastic_port% }
#        default: { host: '%env(ELASTIC_HOST)%', port: '%env(ELASTIC_PORT)%' }
#        default: { host: 172.18.0.16, port: '%env(ELASTIC_PORT)%' }
        default: { url: '%elastic_host%' }
#    serializer:
#        callback_class: FOS\ElasticaBundle\Serializer\Callback
#        serializer: serializer

    indexes:
        randomovies:
            client: default

#            settings:
#                analysis:
#                    analyzer:
#                        title_analyzer:
#                            type: custom
#                            tokenizer: nGram
#    #                        filter: [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
#                            filter: [lowercase]
#                    tokenizer:
#                        nGram:
#                            type:     nGram
#                            min_gram: 1
#                            max_gram: 2

            types:
                movie:
                    # config trouvée sur le site de l'afsy
                    properties:
                        genre: ~
#                        title: { boost: 10, analyzer: title_analyzer }
                        title: { boost: 10 }
                        synopsis: ~
                        year: ~
                        duration: ~
                        rating: ~
                    persistence:
                        driver: orm
                        model: Randomovies\Entity\Movie
                        provider: ~
                        listener: ~
                        finder: ~
                        repository: Randomovies\SearchRepository\MovieRepository

#                    mappings:
#                        id:
#                            type: integer
#                        title: { search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string }
#                        director: ~
#                        actors: ~
#                        year:
#                            type: integer
#                        duration:
#                            type: integer
#                        synopsis: ~
#                        rating:
#                            type: integer
#                        genre: ~
#                    persistence:
#                        driver: orm
#                        model: Randomovies\Entity\Movie
#                        finder: ~
#                        provider: ~
#                        listener: ~
#                        repository: Randomovies\Entity\MovieSearchRepository