fos_elastica:
    clients:    
#        default: { host: '%env(ELASTIC_HOST)%', port: '%env(ELASTIC_PORT)%' }
        default: { url: '%elastic_host%' }
        
#    serializer:
#        callback_class: FOS\ElasticaBundle\Serializer\Callback
#        serializer: serializer

    indexes:
        randomovies:
            client: default

#            settings:
#                analysis:
#                    analyzer:
#                        title_analyzer:
#                            type: custom
#                            tokenizer: nGram
#                            filter: [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
#                            filter: [lowercase]
#                    tokenizer:
#                        nGram:
#                            type:     nGram
#                            min_gram: 1
#                            max_gram: 2
            
            settings:
                index:
                    analysis:
                        analyzer:
                            lowercase_analyser:
                                type: custom
                                tokenizer: letter
                                filter: [lowercase]
                            french_analyser:
                                type: custom
                                tokenizer: letter
                                filter: ["asciifolding", "lowercase", "french_stem", "stop_fr"]
                        filter:
                            stop_fr:
                                type: "stop"
                                stopwords: ["l", "m", "t", "qu", "n", "s", "j", "d"]
            
            types:
                movie:                    
                    properties:                        
                        title: { analyser: lowercase_analyser, boost: 10 }
                        genre: ~
                        year: { type: integer }
                        duration: { type: integer }                            
                        rating: { type: integer }
                        director: { analyser: lowercase_analyser }
                        actors: { analyser: lowercase_analyser }
                        synopsis: { analyser: french_analyser }
                    persistence:
                        driver: orm
                        model: Randomovies\Entity\Movie
                        provider: ~
                        listener: ~
                        finder: ~
                        repository: Randomovies\SearchRepository\MovieRepository