# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Randomovies\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: user_db
        user_db:
            entity:
                class: Randomovies:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        admin_login:
#            anonymous: ~
#            form_login:
#                login_path: login
#                check_path: login
#            logout:
#                path: /logout
#                target: /
#            provider: in_memory

#        user_login:
#            anonymous: ~
#            form_login:
#                login_path: user-login
#                check_path: user-login
#            logout:
#                path: /logout
#                target: /
#            http_basic: ~
#            provider: user_db

        
#        admin:
#            pattern: ^/admin
#            form_login:
#                login_path: login
#                check_path: login
#            logout:
#                path: /logout
#                target: /
#            provider: in_memory

#        user:
#            pattern: ^/user
#            form_login:
#                login_path: user-login
#                check_path: user-login
#            logout:
#                path: /logout
#                target: /
#            http_basic: ~
#            provider: user_db

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
#            provider: user_db

    access_control:
        - { path: ^/user, roles: [ ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/admin, roles: ROLE_ADMIN }
