services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Randomovies\Command\:
        resource: '../src/Command'
    
    randomovies.listener.movie:
        class: Randomovies\EventListener\MovieListener
        arguments: ["%posters_directory%"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            
    randomovies.listener.user:
        class: Randomovies\EventListener\UserListener
        arguments: ["%users_photos_directory%"]
        tags:            
            - { name: doctrine.event_listener, event: postUpdate }
    
    app.twig.random_movies_extension:
        class: Randomovies\Twig\Extension\RandomMoviesExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    app.randomovies_mailer:
        public: true
        class: Randomovies\Service\Mailer
        arguments:
            - "@mailer"
            - "%mailer_sender%"
            - "@templating"

    app.extractor.movie:
        class: Randomovies\Extractor\MovieExtractor
        arguments:
            - "@validator"